const spots = [
  {id:'kona',name:'Kona',country:'Hawaii, USA',region:'북아메리카',coords:[19.64,-155.99],level:'beginner',depth:'12 / 30m',visibility:'20–30m',temp:'27℃',current:'약함',cert:'AOW 권장',best:'연중',rain:'건기 4–10월',avoid:'큰 파도 시기(12–2월)',creatures:['만타레이','돌고래','바다거북'],season:'만타레이: 연중 · 최고 확률 11–4월',feature:'Manta Night Dive',image:'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=900&q=80',months:[1,2,3,4,5,6,7,8,9,10,11,12]},
  {id:'palau',name:'Blue Corner',country:'Palau, Micronesia',region:'오세아니아',coords:[7.13,134.23],level:'advanced',depth:'15 / 40m',visibility:'25–40m',temp:'29℃',current:'강함',cert:'AOW + 조류다이빙 경험',best:'11–4월',rain:'건기 11–4월',avoid:'우기 7–10월',creatures:['상어','만타레이','바다거북'],season:'상어: 연중 · 만타레이: 12–3월',feature:'세계적인 드리프트 다이빙',image:'https://images.unsplash.com/photo-1546026423-cc4642628d2b?auto=format&fit=crop&w=900&q=80',months:[11,12,1,2,3,4]},
  {id:'maldives',name:'Hanifaru Bay',country:'Baa Atoll, Maldives',region:'아시아',coords:[5.23,73.13],level:'intermediate',depth:'5 / 18m',visibility:'10–25m',temp:'29℃',current:'보통',cert:'OW 이상',best:'6–11월',rain:'우기 5–10월',avoid:'5월 전후 강한 비',creatures:['만타레이','고래상어','상어'],season:'만타레이: 6–11월 · 최고 확률 8–10월',feature:'만타레이 대집결',image:'https://images.unsplash.com/photo-1518467166778-b88f373ffec7?auto=format&fit=crop&w=900&q=80',months:[6,7,8,9,10,11]},
  {id:'komodo',name:'Manta Point',country:'Komodo, Indonesia',region:'아시아',coords:[-8.57,119.52],level:'intermediate',depth:'8 / 25m',visibility:'15–30m',temp:'27℃',current:'보통~강함',cert:'AOW 권장',best:'4–11월',rain:'건기 4–11월',avoid:'우기 1–3월',creatures:['만타레이','상어','누디브랜치'],season:'만타레이: 연중 · 최고 확률 12–2월',feature:'만타 클리닝 스테이션',image:'https://images.unsplash.com/photo-1568430462989-44163eb1752f?auto=format&fit=crop&w=900&q=80',months:[4,5,6,7,8,9,10,11]},
  {id:'sipadan',name:'Sipadan Island',country:'Sabah, Malaysia',region:'아시아',coords:[4.12,118.63],level:'intermediate',depth:'10 / 40m',visibility:'20–35m',temp:'29℃',current:'보통',cert:'AOW 권장',best:'4–12월',rain:'건기 4–9월',avoid:'1–2월 강풍',creatures:['상어','바다거북','돌고래'],season:'바다거북·상어: 연중',feature:'거북이와 바라쿠다 토네이도',image:'https://images.unsplash.com/photo-1559827260-dc66d52bef19?auto=format&fit=crop&w=900&q=80',months:[4,5,6,7,8,9,10,11,12]},
  {id:'tubbataha',name:'Tubbataha Reefs',country:'Sulu Sea, Philippines',region:'아시아',coords:[8.88,119.88],level:'advanced',depth:'12 / 45m',visibility:'25–40m',temp:'28℃',current:'강함',cert:'AOW + 50 dives',best:'3–6월',rain:'건기 3–6월',avoid:'7–2월 폐쇄 · 태풍',creatures:['상어','고래','돌고래'],season:'고래상어: 3–5월 · 상어: 연중',feature:'라이브어보드 전용 보호구역',image:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=80',months:[3,4,5,6]},
  {id:'raja',name:'Cape Kri',country:'Raja Ampat, Indonesia',region:'아시아',coords:[0.57,130.68],level:'intermediate',depth:'8 / 30m',visibility:'15–30m',temp:'29℃',current:'보통~강함',cert:'AOW 권장',best:'10–4월',rain:'우기 6–9월',avoid:'6–9월 거친 바다',creatures:['피그미해마','상어','만타레이','산호'],season:'만타레이: 10–4월 · 피그미해마: 연중',feature:'세계 최고 수준의 생물다양성',image:'https://images.unsplash.com/photo-1583212292454-1fe6229603b7?auto=format&fit=crop&w=900&q=80',months:[10,11,12,1,2,3,4]},
  {id:'ningaloo',name:'Ningaloo Reef',country:'Western Australia',region:'오세아니아',coords:[-22.02,113.94],level:'beginner',depth:'5 / 20m',visibility:'15–30m',temp:'25℃',current:'약함',cert:'OW 이상',best:'3–7월',rain:'건조한 연중',avoid:'1–2월 고온',creatures:['고래상어','혹등고래','바다거북'],season:'고래상어: 3–7월 · 혹등고래: 7–10월',feature:'고래상어와 스노클링',image:'https://images.unsplash.com/photo-1560275619-4662e36fa65c?auto=format&fit=crop&w=900&q=80',months:[3,4,5,6,7]},
  {id:'socorro',name:'Socorro Islands',country:'Mexico',region:'중앙아메리카',coords:[18.78,-110.95],level:'advanced',depth:'15 / 45m',visibility:'20–40m',temp:'24℃',current:'강함',cert:'AOW + 50 dives',best:'11–5월',rain:'건기 11–5월',avoid:'6–10월 접근 불가',creatures:['만타레이','상어','혹등고래','돌고래'],season:'만타레이: 11–5월 · 혹등고래: 1–4월',feature:'대양 만타와 거대 해양생물',image:'https://images.unsplash.com/photo-1518467166778-b88f373ffec7?auto=format&fit=crop&w=900&q=80',months:[11,12,1,2,3,4,5]},
  {id:'cozumel',name:'Palancar Reef',country:'Cozumel, Mexico',region:'중앙아메리카',coords:[20.31,-87.02],level:'beginner',depth:'8 / 30m',visibility:'25–40m',temp:'27℃',current:'약함~보통',cert:'OW 이상',best:'11–5월',rain:'건기 11–4월',avoid:'8–10월 허리케인',creatures:['바다거북','상어','산호'],season:'바다거북: 연중 · 황소상어: 11–3월',feature:'맑은 카리브해 드리프트',image:'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=900&q=80',months:[11,12,1,2,3,4,5]},
  {id:'galapagos',name:'Wolf Island',country:'Galápagos, Ecuador',region:'중앙아메리카',coords:[1.39,-91.82],level:'advanced',depth:'18 / 45m',visibility:'15–30m',temp:'24℃',current:'강함',cert:'AOW + 100 dives',best:'6–11월',rain:'가루아 시즌 6–11월',avoid:'강한 조류 상시 주의',creatures:['상어','고래상어','돌고래'],season:'고래상어: 6–11월 · 귀상어: 연중',feature:'망치상어 스쿨링',image:'https://images.unsplash.com/photo-1546026423-cc4642628d2b?auto=format&fit=crop&w=900&q=80',months:[6,7,8,9,10,11]},
  {id:'sodwana',name:'Sodwana Bay',country:'KwaZulu-Natal, South Africa',region:'아프리카',coords:[-27.54,32.67],level:'intermediate',depth:'10 / 35m',visibility:'15–30m',temp:'25℃',current:'보통',cert:'AOW 권장',best:'11–5월',rain:'여름 우기 11–3월',avoid:'6–8월 큰 너울',creatures:['고래상어','상어','돌고래'],season:'고래상어: 11–3월 · 혹등고래: 6–11월',feature:'인도양의 다채로운 산호초',image:'https://images.unsplash.com/photo-1470165518243-ff1d8da9d4e8?auto=format&fit=crop&w=900&q=80',months:[11,12,1,2,3,4,5]},
  {id:'dahab',name:'Blue Hole',country:'Dahab, Egypt',region:'아프리카',coords:[28.57,34.54],level:'advanced',depth:'20 / 100m+',visibility:'25–40m',temp:'25℃',current:'보통',cert:'AOW / 테크니컬',best:'3–6월, 9–11월',rain:'건조한 연중',avoid:'7–8월 폭염',creatures:['산호','누디브랜치','돌고래'],season:'돌고래: 연중 · 산호: 연중',feature:'전설적인 수직 블루홀',image:'https://images.unsplash.com/photo-1484291470158-b8f8d608850d?auto=format&fit=crop&w=900&q=80',months:[3,4,5,6,9,10,11]},
  {id:'silfra',name:'Silfra Fissure',country:'Thingvellir, Iceland',region:'유럽',coords:[64.26,-21.12],level:'beginner',depth:'5 / 18m',visibility:'80–100m',temp:'3℃',current:'약함',cert:'Dry Suit Specialty',best:'연중',rain:'변덕스러운 날씨',avoid:'겨울 폭설·도로 상황',creatures:['산호'],season:'빙하수 시야: 연중',feature:'두 대륙 사이를 다이빙',image:'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=900&q=80',months:[1,2,3,4,5,6,7,8,9,10,11,12]}
];

spots.push(
  {id:'molokini-backwall',name:'Molokini Backwall',country:'Maui, Hawaii, USA',region:'북아메리카',coords:[20.63,-156.49],level:'advanced',depth:'24 / 40m',visibility:'30–45m',temp:'25℃',current:'보통~강함',cert:'AOW + 드리프트 경험',best:'5–9월',rain:'건기 4–10월',avoid:'큰 너울·강한 조류',creatures:['상어','만타레이','돌고래','혹등고래'],season:'혹등고래: 10–3월',feature:'화산 분화구 외벽의 월·드리프트',image:'https://images.unsplash.com/photo-1546026423-cc4642628d2b?auto=format&fit=crop&w=900&q=80',months:[5,6,7,8,9],sourceName:'Zentacle',sourceUrl:'https://www.zentacle.com/loc/us/hi/maui/molokini/molokini-backwall'},
  {id:'lanai-cathedrals',name:'Lanai Cathedrals',country:'Lanai, Hawaii, USA',region:'북아메리카',coords:[20.77,-156.90],level:'beginner',depth:'12 / 20m',visibility:'20–30m',temp:'25℃',current:'약함',cert:'OW 이상',best:'5–9월',rain:'건기 4–10월',avoid:'남쪽 큰 너울',creatures:['상어','바다거북','돌고래'],season:'안정적인 시야: 여름',feature:'빛기둥이 드는 용암 동굴',image:'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=900&q=80',months:[5,6,7,8,9],sourceName:'Zentacle',sourceUrl:'https://www.zentacle.com/loc/us/hi/lanai/lanai-cathedrals'},
  {id:'turtle-canyon',name:'Turtle Canyon Reef',country:'Oahu, Hawaii, USA',region:'북아메리카',coords:[21.27,-157.86],level:'beginner',depth:'6 / 14m',visibility:'15–25m',temp:'26℃',current:'약함',cert:'OW 이상',best:'4–10월',rain:'건기 4–10월',avoid:'남쪽 너울',creatures:['바다거북','문어','산호'],season:'바다거북: 연중',feature:'와이키키 앞바다 거북 클리닝 스테이션',image:'https://images.unsplash.com/photo-1559827260-dc66d52bef19?auto=format&fit=crop&w=900&q=80',months:[4,5,6,7,8,9,10],sourceName:'Zentacle',sourceUrl:'https://www.zentacle.com/loc/us/hi/oahu/turtle-canyon-reef'},
  {id:'sea-tiger',name:'Sea Tiger Wreck',country:'Oahu, Hawaii, USA',region:'북아메리카',coords:[21.28,-157.87],level:'intermediate',depth:'25 / 35m',visibility:'20–30m',temp:'26℃',current:'약함~보통',cert:'AOW 권장',best:'4–10월',rain:'건기 4–10월',avoid:'감압 한계·난파선 관통',creatures:['가오리','문어','바다거북'],season:'해양생물: 연중',feature:'호놀룰루 인근 침선 다이빙',image:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=80',months:[4,5,6,7,8,9,10],sourceName:'Zentacle',sourceUrl:'https://www.zentacle.com/loc/us/hi/oahu/sea-tiger'},
  {id:'la-jolla-cove',name:'La Jolla Cove',country:'California, USA',region:'북아메리카',coords:[32.85,-117.27],level:'beginner',depth:'6 / 18m',visibility:'5–15m',temp:'17℃',current:'약함~보통',cert:'OW 이상',best:'8–11월',rain:'겨울 우기',avoid:'큰 서프·낮은 시야',creatures:['바다사자','가오리','상어'],season:'레오파드상어: 7–9월',feature:'켈프와 해양보호구역 쇼어 다이빙',image:'https://images.unsplash.com/photo-1560275619-4662e36fa65c?auto=format&fit=crop&w=900&q=80',months:[8,9,10,11],sourceName:'Zentacle',sourceUrl:'https://www.zentacle.com/loc/us/ca/san-diego/la-jolla-cove'},
  {id:'casino-point',name:'Casino Point Dive Park',country:'Catalina Island, California, USA',region:'북아메리카',coords:[33.35,-118.33],level:'beginner',depth:'6 / 30m',visibility:'12–25m',temp:'18℃',current:'약함',cert:'OW 이상',best:'7–11월',rain:'겨울 우기',avoid:'주말 혼잡·차가운 수온',creatures:['바다사자','가오리','켈프'],season:'켈프 숲: 연중',feature:'계단 입수형 해양공원',image:'https://images.unsplash.com/photo-1583212292454-1fe6229603b7?auto=format&fit=crop&w=900&q=80',months:[7,8,9,10,11],sourceName:'Zentacle',sourceUrl:'https://www.zentacle.com/loc/us/ca/catalina-island/casino-point'},
  {id:'blue-heron-bridge',name:'Blue Heron Bridge',country:'Florida, USA',region:'북아메리카',coords:[26.78,-80.04],level:'beginner',depth:'3 / 6m',visibility:'3–12m',temp:'26℃',current:'약함~강함',cert:'OW 이상',best:'4–9월',rain:'여름 우기',avoid:'만조 전후 외 시간·보트 통로',creatures:['해마','문어','가오리','누디브랜치'],season:'매크로 생물: 연중',feature:'만조에 맞춰 입수하는 유명 쇼어 다이빙',image:'https://images.unsplash.com/photo-1484291470158-b8f8d608850d?auto=format&fit=crop&w=900&q=80',months:[4,5,6,7,8,9],sourceName:'Zentacle',sourceUrl:'https://www.zentacle.com/loc/us/fl/southeast-florida/blue-heron-bridge'},
  {id:'spiegel-grove',name:'USS Spiegel Grove',country:'Key Largo, Florida, USA',region:'북아메리카',coords:[25.07,-80.31],level:'advanced',depth:'20 / 40m',visibility:'15–30m',temp:'26℃',current:'보통~강함',cert:'AOW + 난파선 권장',best:'4–8월',rain:'여름 소나기',avoid:'강한 조류·관통 다이빙',creatures:['상어','바다거북','그루퍼'],season:'대형 어류: 연중',feature:'길이 155m의 대형 인공어초 침선',image:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=80',months:[4,5,6,7,8],sourceName:'Zentacle',sourceUrl:'https://www.zentacle.com/loc/us/fl/florida-keys/uss-spiegel-grove'},
  {id:'homestead-crater',name:'Homestead Crater',country:'Utah, USA',region:'북아메리카',coords:[40.53,-111.49],level:'beginner',depth:'5 / 20m',visibility:'10–20m',temp:'34℃',current:'없음',cert:'OW 교육 가능',best:'연중',rain:'실내형 온천',avoid:'예약 없는 방문',creatures:['민물고기'],season:'수온: 연중 일정',feature:'석회암 돔 안의 온천 다이빙',image:'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=900&q=80',months:[1,2,3,4,5,6,7,8,9,10,11,12],sourceName:'Zentacle',sourceUrl:'https://www.zentacle.com/loc/us/ut/homestead-crater'},
  {id:'balmorhea',name:'Balmorhea Springs',country:'Texas, USA',region:'북아메리카',coords:[30.94,-103.79],level:'beginner',depth:'3 / 8m',visibility:'15–25m',temp:'22℃',current:'없음',cert:'OW 이상',best:'연중',rain:'건조한 기후',avoid:'공원 휴장·보수 일정',creatures:['민물고기','바다거북'],season:'수온: 연중 일정',feature:'사막 속 대형 천연 샘',image:'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=900&q=80',months:[1,2,3,4,5,6,7,8,9,10,11,12],sourceName:'Zentacle',sourceUrl:'https://www.zentacle.com/loc/us/tx/balmorhea-springs'},
  {id:'lake-wazee',name:'Lake Wazee',country:'Wisconsin, USA',region:'북아메리카',coords:[44.29,-90.68],level:'intermediate',depth:'10 / 60m',visibility:'8–15m',temp:'12℃',current:'없음',cert:'AOW + 드라이슈트 권장',best:'5–10월',rain:'대륙성 기후',avoid:'수온약층 아래 저수온',creatures:['민물고기'],season:'최고 시야: 봄·가을',feature:'깊고 맑은 채석장 호수',image:'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=900&q=80',months:[5,6,7,8,9,10],sourceName:'Zentacle',sourceUrl:'https://www.zentacle.com/loc/us/wi/lake-wazee-black-river-falls'},
  {id:'deception-pass',name:'Deception Pass',country:'Washington, USA',region:'북아메리카',coords:[48.41,-122.64],level:'advanced',depth:'15 / 40m',visibility:'5–15m',temp:'10℃',current:'강함',cert:'AOW + 조류 경험',best:'4–9월',rain:'겨울 우기',avoid:'슬랙 타이드 외 입수',creatures:['문어','게','아네모네'],season:'해양생물: 연중',feature:'조류 타이밍이 핵심인 월 드리프트',image:'https://images.unsplash.com/photo-1470165518243-ff1d8da9d4e8?auto=format&fit=crop&w=900&q=80',months:[4,5,6,7,8,9],sourceName:'Zentacle',sourceUrl:'https://www.zentacle.com/loc/us/wa/deception-pass'},
  {id:'san-juan-lime-kiln',name:'Lime Kiln Wall',country:'San Juan Island, Washington, USA',region:'북아메리카',coords:[48.52,-123.15],level:'advanced',depth:'18 / 45m',visibility:'8–20m',temp:'10℃',current:'강함',cert:'AOW + 드라이슈트',best:'5–9월',rain:'겨울 우기',avoid:'슬랙 타이드 외·어려운 입수',creatures:['문어','게','아네모네'],season:'대형 저서생물: 연중',feature:'가파른 계단식 월 쇼어 다이빙',image:'https://images.unsplash.com/photo-1470165518243-ff1d8da9d4e8?auto=format&fit=crop&w=900&q=80',months:[5,6,7,8,9],sourceName:'Zentacle',sourceUrl:'https://www.zentacle.com/loc/us/wa/san-juan-islands'},
  {id:'bonne-terre',name:'Bonne Terre Mine',country:'Missouri, USA',region:'북아메리카',coords:[37.92,-90.56],level:'intermediate',depth:'12 / 30m',visibility:'30m+',temp:'14℃',current:'없음',cert:'OW + 가이드 필수',best:'연중',rain:'지하 광산',avoid:'가이드 구역 이탈',creatures:['민물고기'],season:'시야: 연중 일정',feature:'조명된 수중 광산 트레일',image:'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=900&q=80',months:[1,2,3,4,5,6,7,8,9,10,11,12],sourceName:'Zentacle',sourceUrl:'https://www.zentacle.com/loc/us/mo/bonne-terre-mine'},
  {id:'yongala',name:'SS Yongala',country:'Queensland, Australia',region:'오세아니아',coords:[-19.31,147.63],level:'advanced',depth:'16 / 30m',visibility:'10–25m',temp:'25℃',current:'보통~강함',cert:'AOW 권장',best:'6–11월',rain:'우기 12–3월',avoid:'사이클론·강한 조류',creatures:['가오리','상어','바다거북','그루퍼'],season:'혹등고래: 6–11월',feature:'산호와 대형 어류로 덮인 역사적 침선',image:'https://images.unsplash.com/photo-1546026423-cc4642628d2b?auto=format&fit=crop&w=900&q=80',months:[6,7,8,9,10,11],sourceName:'PADI',sourceUrl:'https://www.padi.com/dive-site/australia/ss-yongala/'},
  {id:'poor-knights',name:'Poor Knights Islands',country:'Northland, New Zealand',region:'오세아니아',coords:[-35.48,174.74],level:'intermediate',depth:'8 / 35m',visibility:'15–30m',temp:'18℃',current:'약함~보통',cert:'AOW 권장',best:'2–5월',rain:'연중 변동',avoid:'겨울 큰 너울',creatures:['가오리','누디브랜치','돌고래'],season:'가오리: 여름',feature:'해식 동굴과 아치가 많은 해양보호구역',image:'https://images.unsplash.com/photo-1583212292454-1fe6229603b7?auto=format&fit=crop&w=900&q=80',months:[2,3,4,5],sourceName:'PADI',sourceUrl:'https://www.padi.com/dive-site/new-zealand/poor-knights-islands/'},
  {id:'thistlegorm',name:'SS Thistlegorm',country:'Red Sea, Egypt',region:'아프리카',coords:[27.81,33.92],level:'advanced',depth:'16 / 32m',visibility:'20–30m',temp:'26℃',current:'보통~강함',cert:'AOW + 난파선 권장',best:'3–5월, 9–11월',rain:'건조한 연중',avoid:'강한 조류·관통 다이빙',creatures:['바라쿠다','거북','산호'],season:'시야: 연중 양호',feature:'2차대전 군수품이 남은 세계적 침선',image:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=80',months:[3,4,5,9,10,11],sourceName:'PADI',sourceUrl:'https://www.padi.com/dive-site/egypt/ss-thistlegorm/'},
  {id:'elphinstone',name:'Elphinstone Reef',country:'Marsa Alam, Egypt',region:'아프리카',coords:[25.31,34.86],level:'advanced',depth:'18 / 40m',visibility:'20–40m',temp:'27℃',current:'강함',cert:'AOW + 드리프트 경험',best:'5–11월',rain:'건조한 연중',avoid:'거친 바다·하강 조류',creatures:['상어','돌고래','산호'],season:'장완흉상어: 10–12월',feature:'홍해 외해의 남북 수직 월',image:'https://images.unsplash.com/photo-1546026423-cc4642628d2b?auto=format&fit=crop&w=900&q=80',months:[5,6,7,8,9,10,11],sourceName:'Divelogs / dive-sites.net',sourceUrl:'https://dive-sites.net/'},
  {id:'zenobia',name:'MS Zenobia',country:'Larnaca, Cyprus',region:'유럽',coords:[34.89,33.66],level:'advanced',depth:'18 / 42m',visibility:'20–30m',temp:'24℃',current:'약함~보통',cert:'AOW + 난파선 권장',best:'5–10월',rain:'겨울 우기',avoid:'관통 다이빙·감압 한계',creatures:['그루퍼','바라쿠다','문어'],season:'시야: 여름 최고',feature:'측면으로 누운 대형 로로선 침선',image:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=80',months:[5,6,7,8,9,10],sourceName:'PADI',sourceUrl:'https://www.padi.com/dive-site/cyprus/zenobia-wreck/'},
  {id:'medes-islands',name:'Medes Islands',country:'Costa Brava, Spain',region:'유럽',coords:[42.05,3.22],level:'beginner',depth:'8 / 30m',visibility:'15–25m',temp:'20℃',current:'약함~보통',cert:'OW 이상',best:'5–10월',rain:'가을 강수',avoid:'겨울 저수온·북풍',creatures:['그루퍼','문어','산호'],season:'대형 그루퍼: 연중',feature:'지중해 해양보호구역의 동굴과 월',image:'https://images.unsplash.com/photo-1583212292454-1fe6229603b7?auto=format&fit=crop&w=900&q=80',months:[5,6,7,8,9,10],sourceName:'PADI',sourceUrl:'https://www.padi.com/dive-site/spain/medes-islands/'},
  {id:'apo-island',name:'Apo Island',country:'Negros Oriental, Philippines',region:'아시아',coords:[9.08,123.27],level:'beginner',depth:'5 / 30m',visibility:'15–30m',temp:'28℃',current:'약함~보통',cert:'OW 이상',best:'11–5월',rain:'우기 6–10월',avoid:'태풍·강한 조류',creatures:['바다거북','산호','바라쿠다'],season:'바다거북: 연중',feature:'산호 정원과 거북으로 유명한 보호구역',image:'https://images.unsplash.com/photo-1559827260-dc66d52bef19?auto=format&fit=crop&w=900&q=80',months:[11,12,1,2,3,4,5],sourceName:'PADI',sourceUrl:'https://www.padi.com/dive-site/philippines/apo-island/'},
  {id:'richelieu-rock',name:'Richelieu Rock',country:'Andaman Sea, Thailand',region:'아시아',coords:[9.36,98.02],level:'advanced',depth:'10 / 35m',visibility:'15–30m',temp:'28℃',current:'보통~강함',cert:'AOW 권장',best:'2–4월',rain:'우기 5–10월',avoid:'국립공원 폐쇄기·강한 조류',creatures:['고래상어','바라쿠다','누디브랜치'],season:'고래상어: 2–4월',feature:'보라색 연산호로 덮인 외해 피너클',image:'https://images.unsplash.com/photo-1546026423-cc4642628d2b?auto=format&fit=crop&w=900&q=80',months:[2,3,4],sourceName:'PADI',sourceUrl:'https://www.padi.com/dive-site/thailand/richelieu-rock/'},
  {id:'nusa-penida',name:'Crystal Bay',country:'Nusa Penida, Indonesia',region:'아시아',coords:[-8.72,115.46],level:'advanced',depth:'12 / 35m',visibility:'20–35m',temp:'24℃',current:'강함',cert:'AOW + 조류 경험',best:'7–10월',rain:'우기 11–3월',avoid:'하강 조류·저수온',creatures:['개복치','만타레이','바다거북'],season:'개복치: 7–10월',feature:'맑은 시야와 몰라몰라 조우',image:'https://images.unsplash.com/photo-1518467166778-b88f373ffec7?auto=format&fit=crop&w=900&q=80',months:[7,8,9,10],sourceName:'PADI',sourceUrl:'https://www.padi.com/dive-site/indonesia/crystal-bay/'},
  {id:'moalboal',name:'Moalboal Sardine Run',country:'Cebu, Philippines',region:'아시아',coords:[9.95,123.37],level:'beginner',depth:'5 / 25m',visibility:'15–25m',temp:'28℃',current:'약함',cert:'OW 이상',best:'11–5월',rain:'우기 6–10월',avoid:'태풍·혼잡 시간',creatures:['정어리','바다거북','상어'],season:'정어리 떼: 연중',feature:'쇼어에서 만나는 거대한 정어리 군무',image:'https://images.unsplash.com/photo-1568430462989-44163eb1752f?auto=format&fit=crop&w=900&q=80',months:[11,12,1,2,3,4,5],sourceName:'PADI',sourceUrl:'https://www.padi.com/dive-site/philippines/moalboal/'},
  {id:'bonaire-salt-pier',name:'Salt Pier',country:'Bonaire, Caribbean Netherlands',region:'중앙아메리카',coords:[12.10,-68.28],level:'beginner',depth:'6 / 25m',visibility:'20–35m',temp:'28℃',current:'약함',cert:'OW 이상',best:'4–11월',rain:'짧은 우기 11–1월',avoid:'선박 접안·부두 작업',creatures:['바다거북','바라쿠다','산호'],season:'해양생물: 연중',feature:'산호로 덮인 부두 기둥 쇼어 다이빙',image:'https://images.unsplash.com/photo-1559827260-dc66d52bef19?auto=format&fit=crop&w=900&q=80',months:[4,5,6,7,8,9,10,11],sourceName:'PADI',sourceUrl:'https://www.padi.com/dive-site/bonaire/salt-pier/'},
  {id:'darwin-island',name:'Darwin Island',country:'Galápagos, Ecuador',region:'중앙아메리카',coords:[1.68,-92.00],level:'advanced',depth:'18 / 40m',visibility:'10–30m',temp:'23℃',current:'강함',cert:'AOW + 100 dives 권장',best:'6–11월',rain:'가루아 시즌 6–11월',avoid:'강한 조류·거친 표면',creatures:['고래상어','귀상어','돌고래'],season:'고래상어: 6–11월',feature:'대형 원양생물의 세계적 집결지',image:'https://images.unsplash.com/photo-1546026423-cc4642628d2b?auto=format&fit=crop&w=900&q=80',months:[6,7,8,9,10,11],sourceName:'PADI',sourceUrl:'https://www.padi.com/dive-site/ecuador/darwin-island/'},
  {id:'aliwal-shoal',name:'Aliwal Shoal',country:'KwaZulu-Natal, South Africa',region:'아프리카',coords:[-30.27,30.82],level:'advanced',depth:'12 / 30m',visibility:'10–25m',temp:'24℃',current:'보통~강함',cert:'AOW + 드리프트 경험',best:'5–11월',rain:'여름 우기',avoid:'큰 서프·강한 조류',creatures:['상어','가오리','바다거북'],season:'샌드타이거상어: 6–11월',feature:'상어와 침선을 함께 만나는 외해 산호초',image:'https://images.unsplash.com/photo-1546026423-cc4642628d2b?auto=format&fit=crop&w=900&q=80',months:[5,6,7,8,9,10,11],sourceName:'PADI',sourceUrl:'https://www.padi.com/dive-site/south-africa/aliwal-shoal/'}
);

// Zentacle의 개별 페이지 주소 체계는 변경될 수 있어 안정적인 미국 목록 페이지로 연결한다.
spots.filter(spot=>spot.sourceName==='Zentacle').forEach(spot=>{spot.sourceUrl='https://www.zentacle.com/loc/us'});

const state={creature:'',selected:null,wishlist:JSON.parse(localStorage.getItem('scuba-wishlist')||'[]'),visited:JSON.parse(localStorage.getItem('scuba-visited')||'[]'),logs:JSON.parse(localStorage.getItem('scuba-logs')||'[]')};
const $=s=>document.querySelector(s); const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const levelText={beginner:'초급',intermediate:'중급',advanced:'상급'};
const creatureList=[...new Set(spots.flatMap(x=>x.creatures))];
const map=L.map('map',{worldCopyJump:true,minZoom:2}).setView([18,15],2);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors',maxZoom:18}).addTo(map);
let markers=[];
function save(){localStorage.setItem('scuba-wishlist',JSON.stringify(state.wishlist));localStorage.setItem('scuba-visited',JSON.stringify(state.visited));localStorage.setItem('scuba-logs',JSON.stringify(state.logs));$('#logCount').textContent=state.logs.length}
function filtered(){let q=$('#searchInput').value.trim().toLowerCase(),r=$('#regionFilter').value,m=$('#monthFilter').value,l=$('#levelFilter').value;return spots.filter(s=>(!q||[s.name,s.country,...s.creatures,s.feature].join(' ').toLowerCase().includes(q))&&(!r||s.region===r)&&(!m||s.months.includes(+m))&&(!l||s.level===l)&&(!state.creature||s.creatures.includes(state.creature)))}
function render(){const list=filtered();$('#spotCount').textContent=list.length;renderList(list);renderMarkers(list);if(state.selected&&!list.some(x=>x.id===state.selected))showDetail(null)}
function renderList(list){const root=$('#spotList');root.textContent='';list.forEach(s=>{let t=$('#spotTemplate').content.cloneNode(true),a=t.querySelector('.spot-item');a.classList.toggle('selected',state.selected===s.id);let main=t.querySelector('.spot-main');t.querySelector('.difficulty-mark').classList.add(s.level);t.querySelector('b').textContent=s.name;t.querySelector('small').textContent=s.country;let w=t.querySelector('.wish-btn'),v=t.querySelector('.visited-btn');w.classList.toggle('saved',state.wishlist.includes(s.id));v.classList.toggle('done',state.visited.includes(s.id));w.textContent=state.wishlist.includes(s.id)?'♥':'♡';v.textContent=state.visited.includes(s.id)?'✓':'○';main.onclick=()=>selectSpot(s);w.onclick=()=>toggleSaved('wishlist',s.id);v.onclick=()=>toggleSaved('visited',s.id);root.append(t)});if(!list.length)root.innerHTML='<p class="empty-state">조건에 맞는 포인트가 없어요.</p>'}
function renderMarkers(list){markers.forEach(x=>x.remove());markers=list.map(s=>L.marker(s.coords,{icon:L.divIcon({className:'',html:`<div class="map-pin ${s.level}"></div>`,iconSize:[17,17],iconAnchor:[8,8]})}).addTo(map).bindTooltip(`${s.name}<br><small>${levelText[s.level]} · ${s.country}</small>`).on('click',()=>selectSpot(s)))}
function selectSpot(s){state.selected=s.id;map.flyTo(s.coords,Math.max(map.getZoom(),5),{duration:.75});showDetail(s);renderList(filtered())}
function showDetail(s){const root=$('#detailCard');if(!s){root.className='detail-card empty';root.innerHTML='<p>지도 마커 또는 포인트를 선택하면 자세한 다이빙 정보를 볼 수 있어요.</p>';return}root.className='detail-card';let source=s.sourceUrl?`<br>🔗 <b>출처</b> · <a href="${esc(s.sourceUrl)}" target="_blank" rel="noopener noreferrer">${esc(s.sourceName||'원문 보기')}</a>`:'';root.innerHTML=`<div class="detail-content"><img class="detail-image" src="${s.image}" alt="${esc(s.name)} 다이빙 풍경" /><div class="detail-body"><div class="detail-top"><div><p class="eyebrow">${esc(s.region.toUpperCase())}</p><h2 class="detail-title">${esc(s.name)}</h2><span class="location">${esc(s.country)}</span></div><span class="badge">${s.level==='beginner'?'🟢':s.level==='intermediate'?'🟡':'🔴'} ${levelText[s.level]}</span></div><div class="quick-stats"><div><span>🌡 수온</span><b>${s.temp}</b></div><div><span>👁 시야</span><b>${s.visibility}</b></div><div><span>↕ 수심 (평균/최대)</span><b>${s.depth}</b></div><div><span>≋ 조류</span><b>${s.current}</b></div></div><p class="creatures">🐠 <b>대표 생물</b> · ${s.creatures.join(', ')}<br>🌙 <b>특징</b> · ${s.feature}<br>🤿 <b>권장 자격증</b> · ${s.cert}${source}</p><p class="season-note">📅 추천 시기 ${s.best} · ${s.season}<br>☂ ${s.rain} · 피하기: ${s.avoid}</p><div class="detail-actions"><button class="outline-button detail-wish">${state.wishlist.includes(s.id)?'♥ 위시리스트 저장됨':'♡ 가고 싶은 곳'}</button><button class="outline-button detail-visit">${state.visited.includes(s.id)?'✓ 다녀온 곳':'○ 다녀온 곳'}</button></div></div></div>`;root.querySelector('.detail-wish').onclick=()=>toggleSaved('wishlist',s.id);root.querySelector('.detail-visit').onclick=()=>toggleSaved('visited',s.id)}
function toggleSaved(kind,id){let a=state[kind],i=a.indexOf(id);i<0?a.push(id):a.splice(i,1);save();render();showDetail(spots.find(x=>x.id===state.selected))}
function renderChips(){let root=$('#creatureChips');creatureList.forEach(c=>{let b=document.createElement('button');b.className='chip';b.textContent=c;b.onclick=()=>{state.creature=state.creature===c?'':c;renderChips();render()};root.append(b)});updateChips()}
function updateChips(){document.querySelectorAll('.chip').forEach(x=>x.classList.toggle('active',x.textContent===state.creature))}
function renderLogs(){let root=$('#logList'),empty=$('#emptyLogs');root.textContent='';empty.hidden=state.logs.length>0;state.logs.slice().sort((a,b)=>b.date.localeCompare(a.date)).forEach(log=>{let a=document.createElement('article');a.className='log-card';a.innerHTML=`<span class="date">${esc(log.date)}</span><h3>${esc(log.spot)}</h3><div class="log-meta"><span>🤿 #${esc(log.number||'—')}</span><span>↕ ${esc(log.depth||'—')}m</span><span>◷ ${esc(log.duration||'—')}분</span></div><p class="log-note">${esc(log.note||'기록된 메모가 없습니다.')}</p><button class="edit-log">수정</button><button class="delete-log">삭제</button>`;a.querySelector('.edit-log').onclick=()=>openLog(log);a.querySelector('.delete-log').onclick=()=>{if(confirm('이 로그를 삭제할까요?')){state.logs=state.logs.filter(x=>x.id!==log.id);save();renderLogs()}};root.append(a)});let total=state.logs.length,minutes=state.logs.reduce((n,x)=>n+(+x.duration||0),0),deep=Math.max(0,...state.logs.map(x=>+x.depth||0));$('#logStats').innerHTML=[['TOTAL DIVES',total],['TOTAL TIME',minutes+' min'],['MAX DEPTH',deep+' m'],['VISITED SPOTS',new Set(state.logs.map(x=>x.spot)).size]].map(x=>`<article class="stat"><b>${x[1]}</b><span>${x[0]}</span></article>`).join('')}
function openLog(log){$('#dialogTitle').textContent=log?'다이빙 로그 수정':'새 다이빙 로그';['Id','Spot','Date','Number','Depth','Duration','Buddy','Note'].forEach(k=>$('#log'+k).value=log?.[k.charAt(0).toLowerCase()+k.slice(1)]||'');if(!log)$('#logDate').value=new Date().toISOString().slice(0,10);$('#logDialog').showModal()}
$('#logForm').addEventListener('submit',e=>{e.preventDefault();let data={id:$('#logId').value||crypto.randomUUID(),spot:$('#logSpot').value.trim(),date:$('#logDate').value,number:$('#logNumber').value,depth:$('#logDepth').value,duration:$('#logDuration').value,buddy:$('#logBuddy').value.trim(),note:$('#logNote').value.trim()};let i=state.logs.findIndex(x=>x.id===data.id);i<0?state.logs.push(data):state.logs[i]=data;save();renderLogs();$('#logDialog').close()});
document.querySelectorAll('.close-dialog').forEach(b=>b.onclick=()=>$('#logDialog').close());$('#addLogButton').onclick=()=>openLog();
$('#exportLogs').onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state.logs,null,2)],{type:'application/json'}));a.download='scuba-map-logbook.json';a.click();URL.revokeObjectURL(a.href)};
$('#importLogs').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);if(!Array.isArray(x))throw 0;state.logs=x.filter(l=>l&&l.spot&&l.date).map(l=>({...l,id:l.id||crypto.randomUUID()}));save();renderLogs();alert(`${state.logs.length}개의 로그를 가져왔습니다.`)}catch{alert('올바른 로그북 JSON 파일이 아닙니다.')}e.target.value=''};r.readAsText(f)};
document.querySelectorAll('.nav-tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav-tab,.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.view+'View').classList.add('active');if(b.dataset.view==='explore')setTimeout(()=>map.invalidateSize(),50)});
['searchInput','regionFilter','monthFilter','levelFilter'].forEach(id=>$('#'+id).addEventListener(id==='searchInput'?'input':'change',render));$('#resetFilters').onclick=()=>{['searchInput','regionFilter','monthFilter','levelFilter'].forEach(id=>$('#'+id).value='');state.creature='';updateChips();render()};$('#clearSaved').onclick=()=>{state.wishlist=[];state.visited=[];save();render()};
['1월','2월','3월','4월','5월','6월','7월','8월','9월','10월','11월','12월'].forEach((x,i)=>$('#monthFilter').insertAdjacentHTML('beforeend',`<option value="${i+1}">${x}</option>`));renderChips();save();render();renderLogs();
