const spots = [
  {id:'kona',name:'Kona',country:'Hawaii, USA',region:'북아메리카',coords:[19.64,-155.99],level:'beginner',depth:'12 / 30m',visibility:'20–30m',temp:'27℃',current:'약함',cert:'AOW 권장',best:'연중',rain:'건기 4–10월',avoid:'큰 파도 시기(12–2월)',creatures:['만타레이','돌고래','바다거북'],season:'만타레이: 연중 · 최고 확률 11–4월',feature:'Manta Night Dive',image:'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=900&q=80',months:[1,2,3,4,5,6,7,8,9,10,11,12]},
  {id:'palau',name:'Blue Corner',country:'Palau, Micronesia',region:'오세아니아',coords:[7.13,134.23],level:'advanced',depth:'15 / 40m',visibility:'25–40m',temp:'29℃',current:'강함',cert:'AOW + 조류다이빙 경험',best:'11–4월',rain:'건기 11–4월',avoid:'우기 7–10월',creatures:['상어','만타레이','바다거북'],season:'상어: 연중 · 만타레이: 12–3월',feature:'세계적인 드리프트 다이빙',image:'https://images.unsplash.com/photo-1546026423-cc4642628d2b?auto=format&fit=crop&w=900&q=80',months:[11,12,1,2,3,4]},
  {id:'maldives',name:'Hanifaru Bay',country:'Baa Atoll, Maldives',region:'아시아',coords:[5.23,73.13],level:'intermediate',depth:'5 / 18m',visibility:'10–25m',temp:'29℃',current:'보통',cert:'OW 이상',best:'6–11월',rain:'우기 5–10월',avoid:'5월 전후 강한 비',creatures:['만타레이','고래상어','상어'],season:'만타레이: 6–11월 · 최고 확률 8–10월',feature:'만타레이 대집결',image:'https://images.unsplash.com/photo-1518467166778-b88f373ffec7?auto=format&fit=crop&w=900&q=80',months:[6,7,8,9,10,11]},
  {id:'komodo',name:'Manta Point',country:'Komodo, Indonesia',region:'아시아',coords:[-8.57,119.52],level:'intermediate',depth:'8 / 25m',visibility:'15–30m',temp:'27℃',current:'보통~강함',cert:'AOW 권장',best:'4–11월',rain:'건기 4–11월',avoid:'우기 1–3월',creatures:['만타레이','상어','누디브랜치'],season:'만타레이: 연중 · 최고 확률 12–2월',feature:'만타 클리닝 스테이션',image:'https://images.unsplash.com/photo-1568430462989-44163eb1752f?auto=format&fit=crop&w=900&q=80',months:[4,5,6,7,8,9,10,11]},
  {id:'sipadan',name:'Sipadan Island',country:'Sabah, Malaysia',region:'아시아',coords:[4.12,118.63],level:'intermediate',depth:'10 / 40m',visibility:'20–35m',temp:'29℃',current:'보통',cert:'AOW 권장',best:'4–12월',rain:'건기 4–9월',avoid:'1–2월 강풍',creatures:['상어','바다거북','돌고래'],season:'바다거북·상어: 연중',feature:'거북이와 바라쿠다 토네이도',image:'https://images.unsplash.com/photo-1559827260-dc66d52bef19?auto=format&fit=crop&w=900&q=80',months:[4,5,6,7,8,9,10,11,12]},
  {id:'tubbataha',name:'Tubbataha Reefs',country:'Sulu Sea, Philippines',region:'아시아',coords:[8.88,119.88],level:'advanced',depth:'12 / 45m',visibility:'25–40m',temp:'28℃',current:'강함',cert:'AOW + 50 dives',best:'3–6월',rain:'건기 3–6월',avoid:'7–2월 폐쇄 · 태풍',creatures:['상어','고래','돌고래'],season:'고래상어: 3–5월 · 상어: 연중',feature:'라이브어보드 전용 보호구역',image:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=80',months:[3,4,5,6]},
  {id:'raja',name:'Cape Kri',country:'Raja Ampat, Indonesia',region:'아시아',coords:[0.57,130.68],level:'intermediate',depth:'8 / 30m',visibility:'15–30m',temp:'29℃',current:'보통~강함',cert:'AOW 권장',best:'10–4월',rain:'우기 6–9월',avoid:'6–9월 거친 바다',creatures:['피그미해마','상어','만타레이','산호'],season:'만타레이: 10–4월 · 피그미해마: 연중',feature:'세계 최고 수준의 생물다양성',image:'https://images.unsplash.com/photo-1583212292454-1fe6229603b7?auto=format&fit=crop&w=900&q=80',months:[10,11,12,1,2,3,4]},
  {id:'ningaloo',name:'Ningaloo Reef',country:'Western Australia',region:'오세아니아',coords:[-22.02,113.94],level:'beginner',depth:'5 / 20m',visibility:'15–30m',temp:'25℃',current:'약함',cert:'OW 이상',best:'3–7월',rain:'건조한 연중',avoid:'1–2월 고온',creatures:['고래상어','혹등고래','바다거북'],season:'고래상어: 3–7월 · 혹등고래: 7–10월',feature:'고래상어와 스노클링',image:'https://images.unsplash.com/photo-1560275619-4662e36fa65c?auto=format&fit=crop&w=900&q=80',months:[3,4,5,6,7]},
  {id:'socorro',name:'Socorro Islands',country:'Mexico',region:'중앙아메리카',coords:[18.78,-110.95],level:'advanced',depth:'15 / 45m',visibility:'20–40m',temp:'24℃',current:'강함',cert:'AOW + 50 dives',best:'11–5월',rain:'건기 11–5월',avoid:'6–10월 접근 불가',creatures:['만타레이','상어','혹등고래','돌고래'],season:'만타레이: 11–5월 · 혹등고래: 1–4월',feature:'대양 만타와 거대 해양생물',image:'https://images.unsplash.com/photo-1518467166778-b88f373ffec7?auto=format&fit=crop&w=900&q=80',months:[11,12,1,2,3,4,5]},
  {id:'cozumel',name:'Palancar Reef',country:'Cozumel, Mexico',region:'중앙아메리카',coords:[20.31,-87.02],level:'beginner',depth:'8 / 30m',visibility:'25–40m',temp:'27℃',current:'약함~보통',cert:'OW 이상',best:'11–5월',rain:'건기 11–4월',avoid:'8–10월 허리케인',creatures:['바다거북','상어','산호'],season:'바다거북: 연중 · 황소상어: 11–3월',feature:'맑은 카리브해 드리프트',image:'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=900&q=80',months:[11,12,1,2,3,4,5]},
  {id:'galapagos',name:'Wolf Island',country:'Galápagos, Ecuador',region:'중앙아메리카',coords:[1.39,-91.82],level:'advanced',depth:'18 / 45m',visibility:'15–30m',temp:'24℃',current:'강함',cert:'AOW + 100 dives',best:'6–11월',rain:'가루아 시즌 6–11월',avoid:'강한 조류 상시 주의',creatures:['상어','고래상어','돌고래'],season:'고래상어: 6–11월 · 귀상어: 연중',feature:'망치상어 스쿨링',image:'https://images.unsplash.com/photo-1546026423-cc4642628d2b?auto=format&fit=crop&w=900&q=80',months:[6,7,8,9,10,11]},
  {id:'sodwana',name:'Sodwana Bay',country:'KwaZulu-Natal, South Africa',region:'아프리카',coords:[-27.54,32.67],level:'intermediate',depth:'10 / 35m',visibility:'15–30m',temp:'25℃',current:'보통',cert:'AOW 권장',best:'11–5월',rain:'여름 우기 11–3월',avoid:'6–8월 큰 너울',creatures:['고래상어','상어','돌고래'],season:'고래상어: 11–3월 · 혹등고래: 6–11월',feature:'인도양의 다채로운 산호초',image:'https://images.unsplash.com/photo-1470165518243-ff1d8da9d4e8?auto=format&fit=crop&w=900&q=80',months:[11,12,1,2,3,4,5]},
  {id:'dahab',name:'Blue Hole',country:'Dahab, Egypt',region:'아프리카',coords:[28.57,34.54],level:'advanced',depth:'20 / 100m+',visibility:'25–40m',temp:'25℃',current:'보통',cert:'AOW / 테크니컬',best:'3–6월, 9–11월',rain:'건조한 연중',avoid:'7–8월 폭염',creatures:['산호','누디브랜치','돌고래'],season:'돌고래: 연중 · 산호: 연중',feature:'전설적인 수직 블루홀',image:'https://images.unsplash.com/photo-1484291470158-b8f8d608850d?auto=format&fit=crop&w=900&q=80',months:[3,4,5,6,9,10,11]},
  {id:'silfra',name:'Silfra Fissure',country:'Thingvellir, Iceland',region:'유럽',coords:[64.26,-21.12],level:'beginner',depth:'5 / 18m',visibility:'80–100m',temp:'3℃',current:'약함',cert:'Dry Suit Specialty',best:'연중',rain:'변덕스러운 날씨',avoid:'겨울 폭설·도로 상황',creatures:['산호'],season:'빙하수 시야: 연중',feature:'두 대륙 사이를 다이빙',image:'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=900&q=80',months:[1,2,3,4,5,6,7,8,9,10,11,12]}
];

const state={creature:'',selected:null,wishlist:JSON.parse(localStorage.getItem('scuba-wishlist')||'[]'),visited:JSON.parse(localStorage.getItem('scuba-visited')||'[]'),logs:JSON.parse(localStorage.getItem('scuba-logs')||'[]')};
const $=s=>document.querySelector(s); const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const levelText={beginner:'초급',intermediate:'중급',advanced:'상급'};
const creatureList=[...new Set(spots.flatMap(x=>x.creatures))];
const map=L.map('map',{worldCopyJump:true,minZoom:2}).setView([18,15],2);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors',maxZoom:18}).addTo(map);
let markers=[];
function save(){localStorage.setItem('scuba-wishlist',JSON.stringify(state.wishlist));localStorage.setItem('scuba-visited',JSON.stringify(state.visited));localStorage.setItem('scuba-logs',JSON.stringify(state.logs));$('#logCount').textContent=state.logs.length}
function filtered(){let q=$('#searchInput').value.trim().toLowerCase(),r=$('#regionFilter').value,m=$('#monthFilter').value,l=$('#levelFilter').value;return spots.filter(s=>(!q||[s.name,s.country,...s.creatures,s.feature].join(' ').toLowerCase().includes(q))&&(!r||s.region===r)&&(!m||s.months.includes(+m))&&(!l||s.level===l)&&(!state.creature||s.creatures.includes(state.creature)))}
function render(){const list=filtered();$('#spotCount').textContent=list.length;renderList(list);renderMarkers(list);if(state.selected&&!list.some(x=>x.id===state.selected))showDetail(null)}
function renderList(list){const root=$('#spotList');root.textContent='';list.forEach(s=>{let t=$('#spotTemplate').content.cloneNode(true),a=t.querySelector('.spot-item');a.classList.toggle('selected',state.selected===s.id);let main=t.querySelector('.spot-main');t.querySelector('.difficulty-mark').classList.add(s.level);t.querySelector('b').textContent=s.name;t.querySelector('small').textContent=s.country;let w=t.querySelector('.wish-btn'),v=t.querySelector('.visited-btn');w.classList.toggle('saved',state.wishlist.includes(s.id));v.classList.toggle('done',state.visited.includes(s.id));w.textContent=state.wishlist.includes(s.id)?'♥':'♡';v.textContent=state.visited.includes(s.id)?'✓':'○';main.onclick=()=>selectSpot(s);w.onclick=()=>toggleSaved('wishlist',s.id);v.onclick=()=>toggleSaved('visited',s.id);root.append(t)});if(!list.length)root.innerHTML='<p class="empty-state">조건에 맞는 포인트가 없어요.</p>'}
function renderMarkers(list){markers.forEach(x=>x.remove());markers=list.map(s=>L.marker(s.coords,{icon:L.divIcon({className:'',html:`<div class="map-pin ${s.level}"></div>`,iconSize:[17,17],iconAnchor:[8,8]})}).addTo(map).bindTooltip(`${s.name}<br><small>${levelText[s.level]} · ${s.country}</small>`).on('click',()=>selectSpot(s)))}
function selectSpot(s){state.selected=s.id;map.flyTo(s.coords,Math.max(map.getZoom(),5),{duration:.75});showDetail(s);renderList(filtered())}
function showDetail(s){const root=$('#detailCard');if(!s){root.className='detail-card empty';root.innerHTML='<p>지도 마커 또는 포인트를 선택하면 자세한 다이빙 정보를 볼 수 있어요.</p>';return}root.className='detail-card';root.innerHTML=`<div class="detail-content"><img class="detail-image" src="${s.image}" alt="${esc(s.name)} 다이빙 풍경" /><div class="detail-body"><div class="detail-top"><div><p class="eyebrow">${esc(s.region.toUpperCase())}</p><h2 class="detail-title">${esc(s.name)}</h2><span class="location">${esc(s.country)}</span></div><span class="badge">${s.level==='beginner'?'🟢':s.level==='intermediate'?'🟡':'🔴'} ${levelText[s.level]}</span></div><div class="quick-stats"><div><span>🌡 수온</span><b>${s.temp}</b></div><div><span>👁 시야</span><b>${s.visibility}</b></div><div><span>↕ 수심 (평균/최대)</span><b>${s.depth}</b></div><div><span>≋ 조류</span><b>${s.current}</b></div></div><p class="creatures">🐠 <b>대표 생물</b> · ${s.creatures.join(', ')}<br>🌙 <b>특징</b> · ${s.feature}<br>🤿 <b>권장 자격증</b> · ${s.cert}</p><p class="season-note">📅 추천 시기 ${s.best} · ${s.season}<br>☂ ${s.rain} · 피하기: ${s.avoid}</p><div class="detail-actions"><button class="outline-button detail-wish">${state.wishlist.includes(s.id)?'♥ 위시리스트 저장됨':'♡ 가고 싶은 곳'}</button><button class="outline-button detail-visit">${state.visited.includes(s.id)?'✓ 다녀온 곳':'○ 다녀온 곳'}</button></div></div></div>`;root.querySelector('.detail-wish').onclick=()=>toggleSaved('wishlist',s.id);root.querySelector('.detail-visit').onclick=()=>toggleSaved('visited',s.id)}
function toggleSaved(kind,id){let a=state[kind],i=a.indexOf(id);i<0?a.push(id):a.splice(i,1);save();render();showDetail(spots.find(x=>x.id===state.selected))}
function renderChips(){let root=$('#creatureChips');creatureList.forEach(c=>{let b=document.createElement('button');b.className='chip';b.textContent=c;b.onclick=()=>{state.creature=state.creature===c?'':c;renderChips();render()};root.append(b)});updateChips()}
function updateChips(){document.querySelectorAll('.chip').forEach(x=>x.classList.toggle('active',x.textContent===state.creature))}
function renderLogs(){let root=$('#logList'),empty=$('#emptyLogs');root.textContent='';empty.hidden=state.logs.length>0;state.logs.slice().sort((a,b)=>b.date.localeCompare(a.date)).forEach(log=>{let a=document.createElement('article');a.className='log-card';a.innerHTML=`<span class="date">${esc(log.date)}</span><h3>${esc(log.spot)}</h3><div class="log-meta"><span>🤿 #${esc(log.number||'—')}</span><span>↕ ${esc(log.depth||'—')}m</span><span>◷ ${esc(log.duration||'—')}분</span></div><p class="log-note">${esc(log.note||'기록된 메모가 없습니다.')}</p><button class="edit-log">수정</button><button class="delete-log">삭제</button>`;a.querySelector('.edit-log').onclick=()=>openLog(log);a.querySelector('.delete-log').onclick=()=>{if(confirm('이 로그를 삭제할까요?')){state.logs=state.logs.filter(x=>x.id!==log.id);save();renderLogs()}};root.append(a)});let total=state.logs.length,minutes=state.logs.reduce((n,x)=>n+(+x.duration||0),0),deep=Math.max(0,...state.logs.map(x=>+x.depth||0));$('#logStats').innerHTML=[['TOTAL DIVES',total],['TOTAL TIME',minutes+' min'],['MAX DEPTH',deep+' m'],['VISITED SPOTS',new Set(state.logs.map(x=>x.spot)).size]].map(x=>`<article class="stat"><b>${x[1]}</b><span>${x[0]}</span></article>`).join('')}
function openLog(log){$('#dialogTitle').textContent=log?'다이빙 로그 수정':'새 다이빙 로그';['Id','Spot','Date','Number','Depth','Duration','Buddy','Note'].forEach(k=>$('#log'+k).value=log?.[k.charAt(0).toLowerCase()+k.slice(1)]||'');if(!log)$('#logDate').value=new Date().toISOString().slice(0,10);$('#logDialog').showModal()}
$('#logForm').addEventListener('submit',e=>{e.preventDefault();let data={id:$('#logId').value||crypto.randomUUID(),spot:$('#logSpot').value.trim(),date:$('#logDate').value,number:$('#logNumber').value,depth:$('#logDepth').value,duration:$('#logDuration').value,buddy:$('#logBuddy').value.trim(),note:$('#logNote').value.trim()};let i=state.logs.findIndex(x=>x.id===data.id);i<0?state.logs.push(data):state.logs[i]=data;save();renderLogs();$('#logDialog').close()});
document.querySelectorAll('.close-dialog').forEach(b=>b.onclick=()=>$('#logDialog').close());$('#addLogButton').onclick=()=>openLog();
$('#exportLogs').onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state.logs,null,2)],{type:'application/json'}));a.download='scuba-map-logbook.json';a.click();URL.revokeObjectURL(a.href)};
$('#importLogs').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);if(!Array.isArray(x))throw 0;state.logs=x.filter(l=>l&&l.spot&&l.date).map(l=>({...l,id:l.id||crypto.randomUUID()}));save();renderLogs();alert(`${state.logs.length}개의 로그를 가져왔습니다.`)}catch{alert('올바른 로그북 JSON 파일이 아닙니다.')}e.target.value=''};r.readAsText(f)};
document.querySelectorAll('.nav-tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav-tab,.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.view+'View').classList.add('active');if(b.dataset.view==='explore')setTimeout(()=>map.invalidateSize(),50)});
['searchInput','regionFilter','monthFilter','levelFilter'].forEach(id=>$('#'+id).addEventListener(id==='searchInput'?'input':'change',render));$('#resetFilters').onclick=()=>{['searchInput','regionFilter','monthFilter','levelFilter'].forEach(id=>$('#'+id).value='');state.creature='';updateChips();render()};$('#clearSaved').onclick=()=>{state.wishlist=[];state.visited=[];save();render()};
['1월','2월','3월','4월','5월','6월','7월','8월','9월','10월','11월','12월'].forEach((x,i)=>$('#monthFilter').insertAdjacentHTML('beforeend',`<option value="${i+1}">${x}</option>`));renderChips();save();render();renderLogs();
